routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/customers/{costomerNumber?}', function ($costomerNumber="") {
    if($costomerNumber==""){
        return("No customer was provided");
    }

    return view('comment',['costomerNumber'=>$costomerNumber]);
});


Route::resource('books','BookController');

    
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable=['title','author','status',];
public function user(){
    return $this-> belongsTo('App\User');
}
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    public function books(){
        return $this->hasMany('App\Book');
    }
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Book;
use App\User;
use\Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\DB;




class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id = Auth::id();
               if (Gate::denies('manager')) {
                    $boss = DB::table('employees')->where('employee',$id)->first();
                    $id = $boss->manager;
                }
                $user = User::find($id);
                $books = $user->books;
                return view('books.index', compact('books'));
       // $books=Book::all();
      // $id=2;
     // $id=Auth::id();
     //  $books=User::find($id)->books;
        return view('books.index',['books'=>$books]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Gate::denies('manager')) {
            abort(403,"Sorry you are not allowed to create todos..");
        }
 
        return view('books.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    
    {
        if (Gate::denies('manager')) {
          abort(403,"Are you a hacker or what?");
           }
 
        
        $book = new Book();
       // $id = 2;
       $id=Auth::id();
        $book->title = $request->title;
        $book->author = $request->author;
        $book->user_id=$id;
         $book->save();
        return redirect('books');
    

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)

    {
        if (Gate::denies('manager')) {
            abort(403,"Sorry you are not allowed to create todos..");
        }
 
        $book=Book::find($id);
         return view('books.edit',['book'=>$book]);        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     * 
     */
    public function update(Request $request, $id)
    {
        $book=Book::findOrFail($id);
               //employees are not allowed to change the title 
               if (Gate::denies('manager')) {
                   if ($request->has('title'))
                          abort(403,"You are not allowed to edit book..");
               }   
            
                //make sure the todo belongs to the logged in user
               if(!$book->user->id == Auth::id()) return(redirect('books'));
        $book->update($request->except(['_token']));
        if($request->ajax()){
                    
                        return Response::json(array('result' => 'success1','status' => $request->status ), 200);   
                    } else {          
                       return redirect('books');           
                     
       // if (Gate::denies('manager')) {
          //  abort(403,"Sorry you are not allowed to create todos..");
       // }
 

       // $book=Book::find($id);
       // $book->update($request->all());

       // if (!$book->user->id==Auth::id()) return(redirect('books'));
      // $book->update($request->except(['_token']));
       // if($request->ajax()){
         //   return Response::json(array('result'=>'success','status'=>$request->status),200);
   // }
    //return redirect('todos');
}
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Gate::denies('manager')) {
                       abort(403,"Are you a hacker or what?");
               }
        $book=Book::find($id);
        if (!$book->user->id==Auth::id()) return(redirect('books'));
               $book->delete();
            return redirect('books');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/books/edit.blade.php
@extends('layouts.app')

@section('content')
<h1>Update a Book</h1>
<form method='post' action="{{action('BookController@update',$book->id)}}">
    @csrf
    @method('PATCH')

    <div class="form-group">
        <label for ="title"> Book to update</label>
        <input type="text" class= "form-control" name="title" value="{{$book->title}}">
    </div>
    <div >
       
        <input type="text" class= "form-control" name="author" value="{{$book->author}}">
    </div>
    <div class = "form-group">
        <input type="submit" class="form-controll" name="submit" value="update">
    </div>
</form>
<form method='post' action="{{action('BookController@update',$book->id)}}">
    @csrf
    @method('DELETE')

    <div class = "form-group">
        <input type="submit" class="form-controll" name="submit" value="delete">
    </div>
</form>
@endsection

resources/views/books/form.blade.php
@extends('layouts.app')

@section('content')
<h1>Create a new book</h1>
<form method='post' action="{{action('BookController@store')}}">
    {{csrf_field()}}

    <div class="form-group">
    <h2>Add a book</h2>
        <label for ="title">title </label>
        <input type="text" class= "form-control" name="title">
        </div>
        <div>
        <label for ="author">author</label>
        <input type="text" class= "form-control" name="author">
    </div>
    <div class = "form-group">
        <input type="submit" class="form-control" name="submit" value="save">
    </div>
</form>

@endsection

resources/views/books/index.blade.php
@extends('layouts.app')

@section('content')
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
    <h1> Book list</h1>
        <table>
            <tr>
                
                <th>title</th>
                <th>author</th>
            </tr>
            @foreach($books as $book)
            <tr >
            
                <td>  @if ($book->status)
           <input type = 'checkbox' id ="{{$book->id}}" checked>
       @else
           <input type = 'checkbox' id ="{{$book->id}}">
       @endif
       @can('manager')
       <a href="{{route('books.edit',$book->id)}}">
@endcan

         {{$book->title}}</a></td>
                <td>
                @can('manager')
                <a href="{{route('books.edit',$book->id)}}">
                @endcan  {{$book->author}}</a></td>
               
            </tr>
            @endforeach
        </table>
        @can('manager')
        <a href="{{route('books.create')}}">Create a new book</a>
        @endcan
        <script>
      $(document).ready(function(){
          $(":checkbox").click(function(event){
              console.log(event.target.id)
               $.ajax({
                   url: "{{url('books')}}"+'/' + event.target.id,
                   dataType: 'json',
                   type: 'put' ,
                   contentType:'application/json',
                   data:JSON.stringify({'status':event.target.checked, _token:"{{csrf_token()}}"}),
                   processData:false,
                  success: function( data){
                        console.log(JSON.stringify( data ));
                   },
                   error: function(errorThrown ){
                       console.log( errorThrown );
                   }
               });               
           });
       });
   </script>  
    </body>
</html>
@endsection

resources/views/comment.blade.php
<h1> Hello customer number - {{$costomerNumber}} </h1>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>